// Copyright (c) Cosmo Tech.
// Licensed under the MIT license.

export const BREWERY_SELECTORS = {
  scenario: {
    parameters: {
      bar: {
        stockDisabledValue: '[data-cy=stock-value-disabled-input]',
        stockInput: '[id=number-input-stock]',
        restockDisabledValue: '[data-cy=restock_qty-value-disabled-input]',
        restockInput: '[id=number-input-restock_qty]',
        waitersDisabledValue: '[data-cy=nb_waiters-value-disabled-input]',
        waitersInput: '[id=number-input-nb_waiters]',
      },
      fileUpload: {
        tabName: '[data-cy=file_upload_tab]',
        initialStockDataset: '[data-cy=file-upload-initial_stock_dataset]',
      },
      basicTypes: {
        tabName: '[data-cy=basic_types_tab]',
        currency: '[data-cy=currency-textField]',
        currencySelect: '[id=enum-input-currency]',
        currencyOption: 'li[data-cy=$OPTION]',
        currencyInDisabledMode: '[data-cy=currency-value-disabled-input]',
        currencyName: '[data-cy=text-input-currency_name]',
        currencyNameInput: '[id=text-input-currency_name]',
        currencyNameValueInDisabledMode: '[data-cy=currency_name-value-disabled-input]',
        currencyValue: '[data-cy=number-input-currency_value]',
        currencyValueInput: '[id=number-input-currency_value]',
        currencyValueInDisabledMode: '[data-cy=currency_value-value-disabled-input]',
        currencyUsed: '[data-cy=toggle-input-currency_used]',
        currencyUsedInput: '[id=toggle-input-currency_used]',
        currencyUsedValueInDisabledMode: '[data-cy=currency_used-value-disabled-input]',
        startDate: '[data-cy=date-input-start_date]',
        startDateInput: '[id=date-input-start_date]',
        startDateValueInDisabledMode: '[data-cy=start_date-value-disabled-input]',
        averageConsumption: '[data-cy=slider-input-average_consumption]',
        averageConsumptionValueInDisabledMode: '[data-cy="average_consumption-value-disabled-input"]',
      },
      datasetParts: {
        tabName: '[data-cy=dataset_parts_tab]',
        exampleDatasetPart1: '[data-cy=file-upload-example_dataset_part_1]',
        exampleDatasetPart2: '[data-cy=file-upload-example_dataset_part_2]',
      },
      extraDatasetPart: {
        tabName: '[data-cy=extra_dataset_part_tab]',
        exampleDatasetPart3: '[data-cy=file-upload-example_dataset_part_3]',
      },
      customers: {
        tabName: '[data-cy=customers_tab]',
        table: '[data-cy=table-customers]',
      },
      events: {
        tabName: '[data-cy=events_tab]',
        table: '[data-cy=table-events]',
        additionalSeats: '[data-cy=number-input-additional_seats]',
        additionalSeatsDisabledValue: '[data-cy=additional_seats-value-disabled-input]',
        additionalSeatsInput: '[id=number-input-additional_seats]',
        activated: '[data-cy=toggle-input-activated]',
        activatedDisabledValue: '[data-cy=activated-value-disabled-input]',
        activatedInput: '[id=toggle-input-activated]',
        evaluation: '[data-cy=text-input-evaluation]',
        evaluationValueInDisabledMode: '[data-cy=evaluation-value-disabled-input]',
        evaluationInput: '[id=text-input-evaluation]',
      },
      additionalParameters: {
        tabName: '[data-cy=additional_parameters_tab]',
        volumeUnit: '[data-cy=radio-input-volume_unit]',
        volumeUnitDisabledValue: '[data-cy=volume_unit-value-disabled-input]',
        additionalTables: '[data-cy=number-input-additional_tables]',
        additionalTablesValueInDisabledMode: '[data-cy=additional_tables-value-disabled-input]',
        additionalTablesInput: '[id=number-input-additional_tables]',
        comment: '[data-cy=text-input-comment]',
        commentValueInDisabledMode: '[data-cy=comment-value-disabled-input]',
        commentInput: '[id=text-input-comment]',
        additionalDate: '[id=date-input-additional_date]',
        additionalDateValueInDisabledMode: '[data-cy=additional_date-value-disabled-input]',
      },
    },
  },
};
