version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "ci: GitHub Actions"
  labels: ["dependencies"]
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    version-updates:
      applies-to: version-updates
      patterns: ["*"]
      update-types: ["minor", "patch"]
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore"
  labels: ["dependencies"]
