apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmotech-business-webapp.functions-name" . }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  KEYCLOAK_REALM_URL: {{ .Values.keycloakRealmUrl }}
  POWER_BI_TENANT_ID: {{ .Values.powerbiTenantId }}
  POWER_BI_CLIENT_ID: {{ .Values.powerbiClientId }}
  POWER_BI_CLIENT_SECRET: {{ .Values.powerbiClientSecret }}
