sonar.projectKey=azure-sample-webapp-main
sonar.projectName=azure-sample-webapp (main)

sonar.sources=api,src,public,scripts/patch_webapp_server
sonar.tests=tests,cypress

sonar.issue.ignore.multicriteria=noTodoTags,noCypressAssertions
sonar.issue.ignore.multicriteria.noTodoTags.ruleKey=javascript:S1135
sonar.issue.ignore.multicriteria.noTodoTags.resourceKey=**/*
sonar.issue.ignore.multicriteria.noCypressAssertions.ruleKey=javascript:S2699
sonar.issue.ignore.multicriteria.noCypressAssertions.resourceKey=cypress/**/*
