// Copyright (c) Cosmo Tech.
// Licensed under the MIT license.

import { APP_PERMISSIONS, ACL_PERMISSIONS } from './Permissions';
import { APP_ROLES, ACL_ROLES } from './Roles';

// TODO these mappings should probably be moved to the workspace configuration to be available to both front-end and
// back-end (back-end must enforce security on API calls)

export const PERMISSIONS_BY_APP_ROLE = {
  [APP_ROLES.ORGANIZATION.ADMIN]: [APP_PERMISSIONS.ADMIN],
  [APP_ROLES.ORGANIZATION.COLLABORATOR]: [
    APP_PERMISSIONS.SCENARIO.CREATE,
    APP_PERMISSIONS.SCENARIO.DELETE,
    APP_PERMISSIONS.SCENARIO.EDIT_PARAMETERS,
    APP_PERMISSIONS.SCENARIO.EDIT_PERMISSIONS,
    APP_PERMISSIONS.SCENARIO.EDIT_VALIDATION_STATUS,
    APP_PERMISSIONS.SCENARIO.LAUNCH,
    APP_PERMISSIONS.SCENARIO.RENAME,
    APP_PERMISSIONS.SCENARIO.VIEW,
    APP_PERMISSIONS.SCENARIO.VIEW_PERMISSIONS,
    APP_PERMISSIONS.SCENARIO.VIEW_RESULTS,
  ],
  [APP_ROLES.ORGANIZATION.MODELER]: [
    APP_PERMISSIONS.SCENARIO.CREATE,
    APP_PERMISSIONS.SCENARIO.DELETE,
    APP_PERMISSIONS.SCENARIO.EDIT_PARAMETERS,
    APP_PERMISSIONS.SCENARIO.EDIT_PERMISSIONS,
    APP_PERMISSIONS.SCENARIO.EDIT_VALIDATION_STATUS,
    APP_PERMISSIONS.SCENARIO.LAUNCH,
    APP_PERMISSIONS.SCENARIO.RENAME,
    APP_PERMISSIONS.SCENARIO.VIEW,
    APP_PERMISSIONS.SCENARIO.VIEW_PERMISSIONS,
    APP_PERMISSIONS.SCENARIO.VIEW_RESULTS,
  ],
  [APP_ROLES.ORGANIZATION.USER]: [
    // TODO: define specific permissions of ORGANIZATION.USER
    APP_PERMISSIONS.SCENARIO.CREATE,
    APP_PERMISSIONS.SCENARIO.DELETE,
    APP_PERMISSIONS.SCENARIO.EDIT_PARAMETERS,
    APP_PERMISSIONS.SCENARIO.EDIT_PERMISSIONS,
    APP_PERMISSIONS.SCENARIO.EDIT_VALIDATION_STATUS,
    APP_PERMISSIONS.SCENARIO.LAUNCH,
    APP_PERMISSIONS.SCENARIO.RENAME,
    APP_PERMISSIONS.SCENARIO.VIEW,
    APP_PERMISSIONS.SCENARIO.VIEW_PERMISSIONS,
    APP_PERMISSIONS.SCENARIO.VIEW_RESULTS,
  ],
  [APP_ROLES.ORGANIZATION.VIEWER]: [
    APP_PERMISSIONS.SCENARIO.VIEW,
    APP_PERMISSIONS.SCENARIO.VIEW_PERMISSIONS,
    APP_PERMISSIONS.SCENARIO.VIEW_RESULTS,
  ],
  [APP_ROLES.PLATFORM.ADMIN]: [APP_PERMISSIONS.ADMIN],
};

export const PERMISSIONS_BY_ACL_ROLE = {
  [ACL_ROLES.SCENARIO.ADMIN]: [
    ACL_PERMISSIONS.SCENARIO.DELETE,
    ACL_PERMISSIONS.SCENARIO.EDIT_PARAMETERS,
    ACL_PERMISSIONS.SCENARIO.EDIT_PERMISSIONS,
    ACL_PERMISSIONS.SCENARIO.EDIT_VALIDATION_STATUS,
    ACL_PERMISSIONS.SCENARIO.LAUNCH,
    ACL_PERMISSIONS.SCENARIO.RENAME,
    ACL_PERMISSIONS.SCENARIO.VIEW,
    ACL_PERMISSIONS.SCENARIO.VIEW_PERMISSIONS,
    ACL_PERMISSIONS.SCENARIO.VIEW_RESULTS,
  ],
  [ACL_ROLES.SCENARIO.CREATOR]: [
    ACL_PERMISSIONS.SCENARIO.DELETE,
    ACL_PERMISSIONS.SCENARIO.EDIT_PARAMETERS,
    ACL_PERMISSIONS.SCENARIO.EDIT_PERMISSIONS,
    ACL_PERMISSIONS.SCENARIO.EDIT_VALIDATION_STATUS,
    ACL_PERMISSIONS.SCENARIO.LAUNCH,
    ACL_PERMISSIONS.SCENARIO.RENAME,
    ACL_PERMISSIONS.SCENARIO.VIEW,
    ACL_PERMISSIONS.SCENARIO.VIEW_PERMISSIONS,
    ACL_PERMISSIONS.SCENARIO.VIEW_RESULTS,
  ],
  [ACL_ROLES.SCENARIO.WRITER]: [
    ACL_PERMISSIONS.SCENARIO.EDIT_PARAMETERS,
    ACL_PERMISSIONS.SCENARIO.LAUNCH,
    ACL_PERMISSIONS.SCENARIO.RENAME,
    ACL_PERMISSIONS.SCENARIO.VIEW,
    ACL_PERMISSIONS.SCENARIO.VIEW_PERMISSIONS,
    ACL_PERMISSIONS.SCENARIO.VIEW_RESULTS,
  ],
  [ACL_ROLES.SCENARIO.VALIDATOR]: [
    ACL_PERMISSIONS.SCENARIO.EDIT_PARAMETERS,
    ACL_PERMISSIONS.SCENARIO.EDIT_VALIDATION_STATUS,
    ACL_PERMISSIONS.SCENARIO.LAUNCH,
    ACL_PERMISSIONS.SCENARIO.RENAME,
    ACL_PERMISSIONS.SCENARIO.VIEW,
    ACL_PERMISSIONS.SCENARIO.VIEW_PERMISSIONS,
    ACL_PERMISSIONS.SCENARIO.VIEW_RESULTS,
  ],
  [ACL_ROLES.SCENARIO.READER]: [
    ACL_PERMISSIONS.SCENARIO.VIEW,
    ACL_PERMISSIONS.SCENARIO.VIEW_PERMISSIONS,
    ACL_PERMISSIONS.SCENARIO.VIEW_RESULTS,
  ],
};
