// Copyright (c) Cosmo Tech.
// Licensed under the MIT license.

export const RUNNER_ACTIONS_KEY = {
  CREATE_RUNNER: 'CREATE_RUNNER',
  CREATE_SIMULATION_RUNNER: 'CREATE_SIMULATION_RUNNER',
  LIST_ALL_RUNNERS: 'LIST_ALL_RUNNERS',
  STOP_RUNNER: 'STOP_RUNNER',
  STOP_SIMULATION_RUNNER: 'STOP_SIMULATION_RUNNER',
  GET_RUNNER: 'GET_RUNNER',
  START_RUNNER: 'START_RUNNER',
  START_RUNNER_STATUS_POLLING: 'START_RUNNER_STATUS_POLLING',
  UPDATE_AND_START_RUNNER: 'UPDATE_AND_START_RUNNER',
  RENAME_RUNNER: 'RENAME_RUNNER',
  UPDATE_RUNNER: 'UPDATE_RUNNER',
  UPDATE_RUNNER_SECURITY: 'UPDATE_RUNNER_SECURITY',
  SET_ALL_SIMULATION_RUNNERS: 'SET_ALL_SIMULATION_RUNNERS',
  UPDATE_SIMULATION_RUNNER: 'UPDATE_SIMULATION_RUNNER',
  STOP_RUNNER_STATUS_POLLING: 'STOP_RUNNER_STATUS_POLLING',
  STOP_ALL_RUNNERS_STATUS_POLLING: 'STOP_ALL_RUNNERS_STATUS_POLLING',
  DELETE_RUNNER: 'DELETE_RUNNER',
  SET_CURRENT_SIMULATION_RUNNER: 'SET_CURRENT_SIMULATION_RUNNER',
  RESET_CURRENT_SIMULATION_RUNNER: 'RESET_CURRENT_SIMULATION_RUNNER',
  SET_RUNNER_VALIDATION_STATUS: 'SET_RUNNER_VALIDATION_STATUS',
  UPDATE_ETL_RUNNER: 'UPDATE_ETL_RUNNER',
  // FIXME: keys below may no longer be necessary
  GET_ALL_SIMULATION_RUNNERS: 'GET_ALL_SIMULATION_RUNNERS',
  SET_RUNNER_NAME: 'SET_RUNNER_NAME',
  SET_RUNNER_SECURITY: 'SET_RUNNER_SECURITY',
  ADD_RUNNER: 'ADD_RUNNER',
  ADD_RUN: 'ADD_RUN',
  UPDATE_RUN: 'UPDATE_RUN',
  SET_LIST_STATUS: 'SET_LIST_STATUS',
};
