// Copyright (c) Cosmo Tech.
// Licensed under the MIT license.

export const NODE_TYPES = {
  PRODUCTION_RESOURCE_BOTTLENECK: 'PRODUCTION_RESOURCE_BOTTLENECK',
  PRODUCTION_RESOURCE: 'PRODUCTION_RESOURCE',
  STOCK_SHORTAGE: ' STOCK_SHORTAGE',
  STOCK: 'STOCK',
};
