// Copyright (c) Cosmo Tech.
// Licensed under the MIT license.

// Available application actions
export const APPLICATION_ACTIONS_KEY = {
  SET_APPLICATION_STATUS: 'SET_APPLICATION_STATUS',
  GET_ALL_INITIAL_DATA: 'GET_ALL_INITIAL_DATA',
  GET_NON_CRITICAL_ERRORS: 'GET_NON_CRITICAL_ERRORS',
  CLEAR_ALL_ERRORS: 'CLEAR_ALL_ERRORS',
};
