// Copyright (c) Cosmo Tech.
// Licensed under the MIT license.

// Available DATASET actions
export const DATASET_ACTIONS_KEY = {
  GET_ALL_DATASETS: 'GET_ALL_DATASETS',
  SET_ALL_DATASETS: 'SET_ALL_DATASETS',
  SET_DATASET_SECURITY: 'SET_DATASET_SECURITY',
  ADD_DATASET: 'ADD_DATASET',
  SET_CURRENT_DATASET_INDEX: 'SET_CURRENT_DATASET_INDEX',
  DELETE_DATASET: 'DELETE_DATASET',
  CREATE_DATASET: 'CREATE_DATASET',
  UPDATE_DATASET: 'UPDATE_DATASET',
  TRIGGER_SAGA_UPDATE_DATASET: 'TRIGGER_SAGA_UPDATE_DATASET',
  TRIGGER_SAGA_REFRESH_DATASET: 'TRIGGER_SAGA_REFRESH_DATASET',
  TRIGGER_SAGA_START_TWINGRAPH_STATUS_POLLING: 'TRIGGER_SAGA_START_TWINGRAPH_STATUS_POLLING',
};
