// Copyright (c) Cosmo Tech.
// Licensed under the MIT license.

// Available scenario actions
export const SCENARIO_ACTIONS_KEY = {
  GET_ALL_SCENARIOS: 'GET_ALL_SCENARIOS',
  SET_ALL_SCENARIOS: 'SET_ALL_SCENARIOS',
  GET_SCENARIO_TREE: 'GET_SCENARIO_TREE',
  SET_SCENARIO_TREE: 'SET_SCENARIO_TREE',
  GET_CURRENT_SCENARIO: 'GET_CURRENT_SCENARIO',
  SET_CURRENT_SCENARIO: 'SET_CURRENT_SCENARIO',
  FIND_SCENARIO_BY_ID: 'FIND_SCENARIO_BY_ID',
  CREATE_SCENARIO: 'CREATE_SCENARIO',
  UPDATE_AND_LAUNCH_SCENARIO: 'UPDATE_AND_LAUNCH_SCENARIO'
};
