apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmotech-business-webapp.functions-name" . }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  KEYCLOAK_REALM_URL: {{ .Values.keycloak.realmUrl }}
  POWER_BI_TENANT_ID: {{ .Values.powerbi.tenantId }}
  POWER_BI_CLIENT_ID: {{ .Values.powerbi.clientId }}
  POWER_BI_CLIENT_SECRET: {{ .Values.powerbi.clientSecret }}
