import {
  ArrowLeftToLine,
  Database,
  ClipboardList,
  CircleHelp,
  MoreVertical,
  SquareAsterisk,
  CornerDownRight,
  FolderTree,
  CircleCheck,
  Bot,
  Sun,
  Moon,
  Languages,
  SquarePen,
  SquarePlay,
  Table,
  Map,
  ListChecks,
  ChartArea,
  Lightbulb,
  Share,
  TriangleAlert,
  Lock,
} from 'lucide-react';

const Icons = [
  { name: 'ArrowLeftToLine', Icon: ArrowLeftToLine },
  { name: 'Database', Icon: Database },
  { name: 'ClipboardList', Icon: ClipboardList },
  { name: 'CircleHelp', Icon: CircleHelp },
  { name: 'MoreVertical', Icon: MoreVertical },
  { name: 'SquareAsterisk', Icon: SquareAsterisk },
  { name: 'CornerDownRight', Icon: CornerDownRight },
  { name: 'FolderTree', Icon: FolderTree },
  { name: 'CircleCheck', Icon: CircleCheck },
  { name: 'Bot', Icon: Bot },
  { name: 'Sun', Icon: Sun },
  { name: 'Moon', Icon: Moon },
  { name: 'Languages', Icon: Languages },
  { name: 'SquarePen', Icon: SquarePen },
  { name: 'SquarePlay', Icon: SquarePlay },
  { name: 'Table', Icon: Table },
  { name: 'Map', Icon: Map },
  { name: 'ListChecks', Icon: ListChecks },
  { name: 'ChartArea', Icon: ChartArea },
  { name: 'Lightbulb', Icon: Lightbulb },
  { name: 'Share', Icon: Share },
  { name: 'TriangleAlert', Icon: TriangleAlert },
  { name: 'Lock', Icon: Lock },
];

export default Icons;
