name: Create and publish a Docker image

on:
  push:
    branches: ['experimental/webapp_server_docker_image']

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 1
  PUBLIC_URL: /cosmotech-webapp/brewery

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "webapp-server: extract Docker metadata (tags, labels)"
        id: webapp-server-metadata
        uses: docker/metadata-action@v5
        with:
          tags: |
            # set latest tag for default branch
            type=raw,value=latest
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}/webapp-server
      - name: "webapp-server: build and push Docker image"
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: webapp_server/webapp-server.Dockerfile
          push: true
          tags: ${{ steps.webapp-server-metadata.outputs.tags }}
          labels: ${{ steps.webapp-server-metadata.outputs.labels }}
          build-args: |
            "PUBLIC_URL=${{ env.PUBLIC_URL }}"

      - name: "webapp-functions: extract Docker metadata (tags, labels)"
        id: webapp-functions-metadata
        uses: docker/metadata-action@v5
        with:
          tags: |
            # set latest tag for default branch
            type=raw,value=latest
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}/webapp-functions
      - name: "webapp-functions: build and push Docker image"
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: api
          file: webapp_server/webapp-functions.Dockerfile
          push: true
          tags: ${{ steps.webapp-functions-metadata.outputs.tags }}
          labels: ${{ steps.webapp-functions-metadata.outputs.labels }}
