name: Track Dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dependency_track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '24'
          cache: 'yarn'

      # Generate SBOM files

      - parallel:
        - name: Generate SBOM (webapp-server)
          run: yarn dlx -q @cyclonedx/yarn-plugin-cyclonedx -o sbom-webapp-server-dependencies.json
        - name: Generate SBOM (webapp-functions)
          working-directory: ./api
          run: yarn dlx -q @cyclonedx/yarn-plugin-cyclonedx -o ../sbom-webapp-functions-dependencies.json

      # Upload SBOM files

      - parallel:
        # Branch main
        - name: Upload SBOM files (main - webapp-server)
          if: github.ref_name == 'main'
          uses: DependencyTrack/gh-upload-sbom@95c2b5a810450509ef8a67e4f854b42d2ddf7fbf # v4
          with:
            serverhostname: ${{ secrets.DEPENDENCY_TRACK_SERVER_HOSTNAME }}
            apikey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
            project: a75e5d88-27ef-4f7a-8ce6-c3fb8aac8b17
            bomfilename: sbom-webapp-server-dependencies.json
        - name: Upload SBOM files (main - webapp-functions)
          if: github.ref_name == 'main'
          uses: DependencyTrack/gh-upload-sbom@95c2b5a810450509ef8a67e4f854b42d2ddf7fbf # v4
          with:
            serverhostname: ${{ secrets.DEPENDENCY_TRACK_SERVER_HOSTNAME }}
            apikey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
            project: 493e9e7c-ee43-4482-9dd4-d5ad26d6ab9a
            bomfilename: sbom-webapp-functions-dependencies.json
